apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: repo-1356743351
  namespace: argocd
spec:
  encryptedData:
    project: AgAC4PbINzJhOSegYHPVkWewNUz+Sxgt8wCN6cEVDHnwS3N9xYpMPA7iavlESuWznB7lsgjnx60s/eCvujBjpglpNCQ2IpCyOw2I9YaepLS8zPH/wLkF0B9mQMRJ/X3+zKEDfLE0YDk5KARfml7AmYV/t2z6rsUpgZ9eejY/BBlziVin9/kYz7XAmuurTS6JpIVMiVBBrMWfevsCzxCCFw7g/hBCc5zoIH90dqbTMTYh6CI8UYYAAIrAn+LFGfOxNGmzvlBFRnHEBsl36cPkIZL4aJTwMo3ITDPSMsDwYnqwhWOKasR1gdy95FdEzTagc+AErTIX/a6C+wzIsFcgnalzuCpgQ/BMOdHLss2qVWw4+A2wWedXsCd+Qi9eGtonO4/lK624XJvLuLAV9vw24Z5WSqBZHGMVT4Mfk8pzChJXk4TchP97C8jgeVq5KtC/A8kIbCjHySHXUxMjkmUSr2zwKV83k1D5+OAiWyWfoqzzRRQexImOaYriSBfiaB9TmeAMj7bxdKPYixLlkoo/Q3nafl/CQMgrikWN615t3KXaHiVhHpWFlG/Fbnh10yW+SvYnKqB98CC0FARLdKHrArpSDRJSGMlrMYAK6pVE62MEyVqAZhs1uhdR/gcp4YNKsHhcwdKbGptWMjWUXzeg0vM1pCkVk44/cI29piCtFFuoO17Rjup7np9N373Fe8tjKxSvFy6ABTl2
    type: AgC+7PMNfoX1jnZ4RiBE7X5cuxzEwwsETir8FWy75AuuNJ2gZloUvLRe6DE0Hx+9JVPJCXm8rOdK/kGKlm5ICGRJd172a+RfMqp1Hi0hONkKUY3ALMlmWxIo/dE470EoeqOAFMVxwceNLbZ+pGsRG8FOusHVUf/X+YSRE0618y6oNUqfrGtJJGePrHwopibi9iQLSpkW9ErKcReo7+6+AP4aZyU8s+m04vH6NmYjfiE0x06Ol5z9luTDfazW9Jz363MOIHi/BF5q/amSnJsvcM8wLihazFzCcn+WnW8MHDTkv6EfF507Gk+ec9A9X8JHjiMEvl1KSMJUPQmTSfp5hXmVtloxmI2Vr07VL9xGg4hW/93V4HCoSl90JGxSucY4MR4pUfmmCTegUvmPMC78Syx8LmCSpmdNVZnOjT1uB4LFFkG4JetDJ823kBVFw7OmkZioHlXIhhEsIbBIAZbyX3z9ydtB768j7rh1jF0CfUBUYvqc4d8XksUCjdA08sR7LaI/uMzALStWg657x3AdFl1SLO4lpw0TWfxpzlOGC98D+YGtep3hDqsCsQ+dBwJHtXj7KnfGNLftamFXz/M+0LK06gDBTHvZbSPI1FjWhgW0exJNAbDu/bQt34iI+Yx3dRd4+efYPvvWM6zOOt3XwmLcsk2bZ4U7U+Tm2LXPjpMBZuXH1GNpw0SeXIhyheIEYk4ijgA=
    url: AgBc1fwv5D9NrWDtzjiOQmkkSLaS09EKnYiL2hBZth4vA31Rpnbwe8prsu1jj7eG5QUZ+ldUs9Wzp4vBVg0NAr/6csgzCm9HZh6FkCYYGsiuy1Hsrhs8jKcP/Gbl11vGjKlJtmN0WgVcjqUB+2c1JGpW8h5c/iw/nBYhVAsWIeGrp7rHWBouw+4Ga1z02WGnqGlh/p1Kv5p96/6JtggS1/lHefwptNBq3mhxiyTkEphIgJzEMgKo6hRRnnk5VsoOHhXipNB/6BBRqLw5DFJORh2kDmv8IaXldnFWO62zIsaOTUdd50W7WXB2PYg0kvnezcMYCu7xc1bFlAaheXYtzm1CmtVg9OhUHl51rVolmT61tPu0H7Ay1MQV/xemMwGbk13BVvyOD7aza6y6UyjB0e1w1BpUEJbUs4mY+rFA2HIEzMjezOw0O6rpPWPplfoNSfLBXeUD2bZjKqjNjwYGbfOCsL+uYiT0aOiMfAfZoqwRpvGcUxzHcKqIU6vjAEg4ODOnaArIQ1M3QodWK24+sT/8wZowGKknpFZ9ppInzZT+155GaBBAKg20CJSWk8Mn8lotHGasD44s5G0jmDC+VOWrjv7Ny8h1IluHkqNuUjauqm/5IL0g3zSSlrAlqugPmtMJQUtAZ54/Qq4FvCJReyQdLBP3wmMRHWZL4jG4VDM/4xB7FVOOKWzEAff2wA/FVLZPdpXPkk/hK+SVw8zCdAUm28xF469YoVY6/jcheq12eQ==
  template:
    data: null
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: repo-1356743351
      namespace: argocd
    type: Opaque

